### PR TITLE
add chat options menu

### PR DESCRIPTION
**Pull request by fmzbl**

### CODE REVIEW

**Review by jmbejar — COMMENTED** [review]
This happens when collapsing the left sidebad, when the menu is still visible. This issue sounds similar to the one we had when navigating to other parts of the app

image

**Comment by jmbejar** [comment]
@fmzbl Found a solution to the problem dismissing the floating menu from certain regions of the screen. Can you check https://github.com/moxin-org/moxin/pull/150/commits/004cb397d3c738688b44097a842e0e4581d2983c?

**Review by jmbejar — DISMISSED** [review]
There are a bit of cosmetic issues I'd address before merging, but in general it is working now as expected 👍

**Comment by fmzbl** [comment]
> @fmzbl Found a solution to the problem dismissing the floating menu from certain regions of the screen. Can you check [004cb39](https://github.com/moxin-org/moxin/commit/004cb397d3c738688b44097a842e0e4581d2983c)?

Yeah cool, that should fix the panel and navigating issues, we can remove that stuff then.

**Review by jmbejar — APPROVED** [review]

**Pull request merged**
