### PR TITLE
[Backend] replace model databse with github repo

### PR DESCRIPTION
**Pull request by L-jasmine**

### CODE REVIEW

**Comment by jmbejar** [comment]
Hi, I did a quick round of testing, and one question came up.. are now download and likes count values lost from models cards?

This screenshot is from the version we have in `dev` branch. With this changes, the values are all zero.

image

**Comment by juntao** [comment]
Oh. Indeed. The model database is now a GitHub repo and we have no way to dynamically update the download / like count in real-time.

I guess we need to decide whether this is okay from the product point of view?

**Comment by jmbejar** [comment]
> Oh. Indeed. The model database is now a GitHub repo and we have no way to dynamically update the download / like count in real-time.
> 
> I guess we need to decide whether this is okay from the product point of view?

Just to add a bit more of context, also this dropdown would be totally useless if we don't have those information anymore

image

**Review by jmbejar — COMMENTED** [review]
I was testing a bit more and it works great. The search functionality feels much better using this local cache of the models metadata.

However, I'm holding this PR because the downloads/likes functionality is broken, so we may need to discuss what to do to have this merged.

**Comment by L-jasmine** [comment]
> With changes in this PR, the application crashes on startup if the computer is not connected.

ok I will fix this bug so that it can be used offline

**Comment by L-jasmine** [comment]
> I was testing a bit more and it works great. The search functionality feels much better using this local cache of the models metadata.
> 
> However, I'm holding this PR because the downloads/likes functionality is broken, so we may need to discuss what to do to have this merged.

I will set up a github actions in Model-cards, which will collect the download and like of the model in index.json and update it to index.json, and then activate it with a timer every day. Is that okay?

**Comment by heyong4725** [comment]
@L-jasmine your proposal sounds great to me. Thx

**Comment by L-jasmine** [comment]
@jmbejar  I have set up a release page called index_release in [my model-cards repo](https://github.com/L-jasmine/model-cards).  I added an action to fetch data from Hugging Face every day at 00:00 and update the index. json file, and then push the updates to index_release. https://github.com/moxin-org/model-cards/pull/5

But I don’t have permission to create a new release page in moxin-org/model-cards.

**Comment by jmbejar** [comment]
> moxin-org/model-cards#5



> @jmbejar I have set up a release page called index_release in [my model-cards repo](https://github.com/L-jasmine/model-cards). I added an action to fetch data from Hugging Face every day at 00:00 and update the index. json file, and then push the updates to index_release. [moxin-org/model-cards#5](https://github.com/moxin-org/model-cards/pull/5)
> 
> But I don’t have permission to create a new release page in moxin-org/model-cards.

I think I have permissions in `moxin-org/model-cards` but there are others working in this repo (not me!).
@juntao can someone with more familiarity with this repo to review the @L-jasmine PR there and follow up?

**Comment by jmbejar** [comment]
> > [moxin-org/model-cards#5](https://github.com/moxin-org/model-cards/pull/5)
> 
> > @jmbejar I have set up a release page called index_release in [my model-cards repo](https://github.com/L-jasmine/model-cards). I added an action to fetch data from Hugging Face every day at 00:00 and update the index. json file, and then push the updates to index_release. [moxin-org/model-cards#5](https://github.com/moxin-org/model-cards/pull/5)
> > But I don’t have permission to create a new release page in moxin-org/model-cards.
> 
> I think I have permissions in `moxin-org/model-cards` but there are others working in this repo (not me!). @juntao can someone with more familiarity with this repo to review the @L-jasmine PR there and follow up?

It looks it is merged now.. Let me run another little round of testing and merge this PR if everything is OK

**Review by jmbejar — APPROVED** [review]

**Pull request merged**
